name: wind_droughts_processing

channels:
  - conda-forge

dependencies:
  - python
  - numpy
  - scipy
  - xarray
  - netcdf4
  - pandas
  - pip
  - pip:
    - mpi4py
    - dask
    - dask-mpi
    - distributed
